### ISSUE TITLE
funk segmentation error

### ISSUE THREAD

**Issue by cordoval** [docteurklein/event-store#4]
if i mistakenly run php bin/funk without arguments 

~ php bin/funk                                                                           Luiss-MacBook-Pro-3 [3:09:51]
[1]    22223 segmentation fault  php bin/funk

**Comment by cordoval** [comment]
ok :flushed: going to :sleeping: 

:eyes: you

**Comment by docteurklein** [comment]
oh, that's unfortunate :/ Could you paste your php version ?

The same thing here (PHP 5.5.16 (cli) (built: Aug 21 2014 18:34:24)) actually runs correctly the specs located in the `funk` folder.

Or if you have a public link to your repo, i can try to clone it and run it locally.
Thanks!

**Comment by cordoval** [comment]
5.6, did you run it without arguments?

**Comment by docteurklein** [comment]
yep: `php bin/funk`

**Comment by cordoval** [comment]
hmm interesting, maybe because of php5.6?

btw thanks for replying docteur, sometimes it does not get that kind with me https://github.com/Behat/Behat/pull/638#issuecomment-56311842 :cat:

**Comment by docteurklein** [comment]
I'm not sure yet, I can't run a full build on travis (missing database setups & co).

Otherwise, I think those types of PRs match a lot of different topics, and people like to have focused, atomic PR / changes, that's why :)
